version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    restart: always
    depends_on:
      - nginx
      - redis
    env_file:
      - .env
    volumes:
      - static:/static
    ports:
      - 3010:3010
    networks:
      - scud
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - scud
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - scud

volumes:
  static:
  redis:

networks:
  scud:
    driver: bridge
