export const permissions = {
    USERS: {
        CREATE: 'create-users',
        BROWSE: 'browse-users',
        READ: 'read-users',
        UPDATE: 'update-users',
        DELETE: 'delete-users',
    },
    ROLES: {
        CREATE: 'create-roles',
        BROWSE: 'browse-roles',
        READ: 'read-roles',
        UPDATE: 'update-roles',
        DELETE: 'delete-roles',
    },
    PERMISSIONS: {
        BROWSE: 'browse-permissions',
    },
    LICENSES: {
        CREATE: 'create-licenses',
        BROWSE: 'browse-licenses',
        READ: 'read-licenses',
        UPDATE: 'update-licenses',
        DELETE: 'delete-licenses',
    },
    VEHICLES: {
        CREATE: 'create-vehicles',
        BROWSE: 'browse-vehicles',
        READ: 'read-vehicles',
        UPDATE: 'update-vehicles',
        DELETE: 'delete-vehicles',
    },
    BANK_ACCOUNTS: {
        CREATE: 'create-bank-accounts',
        BROWSE: 'browse-bank-accounts',
        READ: 'read-bank-accounts',
        UPDATE: 'update-bank-accounts',
        DELETE: 'delete-bank-accounts',
    },
    SETTINGS: {
        UPDATE: 'update-settings',
        BROWSE: 'browse-settings',
    },
    FARE: {
        CREATE: 'create-fares',
        BROWSE: 'browse-fares',
        READ: 'read-fares',
        UPDATE: 'update-fares',
        DELETE: 'delete-fares',
    },
    CANCEL_REASONS: {
        CREATE: 'create-cancel-reasons',
        BROWSE: 'browse-cancel-reasons',
        READ: 'read-cancel-reasons',
        UPDATE: 'update-cancel-reasons',
        DELETE: 'delete-cancel-reasons',
    },
    INCENTIVES: {
        CREATE: 'create-incentives',
        BROWSE: 'browse-incentives',
        READ: 'read-incentives',
        UPDATE: 'update-incentives',
        DELETE: 'delete-incentives',
    },
    FAQS: {
        CREATE: 'create-faqs',
        BROWSE: 'browse-faqs',
        READ: 'read-faqs',
        UPDATE: 'update-faqs',
        DELETE: 'delete-faqs',
    },
    PROMO: {
        CREATE: 'create-promos',
        BROWSE: 'browse-promos',
        READ: 'read-promos',
        UPDATE: 'update-promos',
        DELETE: 'delete-promos',
    },
    VEHICLE_BRANDS: {
        CREATE: 'create-vehicle-brands',
        BROWSE: 'browse-vehicle-brands',
        READ: 'read-vehicle-brands',
        UPDATE: 'update-vehicle-brands',
        DELETE: 'delete-vehicle-brands',
    },
    NOTIFICATIONS: {
        CREATE: 'create-notifications',
        BROWSE: 'browse-notifications',
        READ: 'read-notifications',
        UPDATE: 'update-notifications',
        DELETE: 'delete-notifications',
    },
    LOCATIONS: {
        CREATE: 'create-locations',
        BROWSE: 'browse-locations',
        READ: 'read-locations',
        UPDATE: 'update-locations',
        DELETE: 'delete-locations',
    },
    SUPERVISORS: {
        BROWSE: 'browse-supervisors',
        UPDATE: 'update-supervisors',
    },
    ACCOUNT_MANAGER: {
        BROWSE: 'browse-account-manager',
    },
    WITHDRAWAL_REQUESTS: {
        CREATE: 'create-withdrawal-requests',
        BROWSE: 'browse-withdrawal-requests',
        UPDATE: 'update-withdrawal-requests',
    },
    SUPPORT: {
        CREATE: 'create-support',
        BROWSE: 'browse-support',
        READ: 'read-support',
        UPDATE: 'update-support',
        DELETE: 'delete-support',
    },
    DISCOUNTS: {
        CREATE: 'create-discounts',
        READ: 'read-discounts',
        BROWSE: 'browse-discounts',
        UPDATE: 'update-discounts',
        DELETE: 'delete-discounts',
    },
    REVIEWS: {
        BROWSE: 'browse-reviews',
        READ: 'read-reviews',
        DELETE: 'delete-reviews',
    },
    TIMEONLINE: {
        BROWSE: 'browse-time-online',
        READ: 'read-time-online',
        DELETE: 'delete-time-online',
    },
    VEHICLE_TYPES: {
        CREATE: 'create-vehicle-types',
        BROWSE: 'browse-vehicle-types',
        READ: 'read-vehicle-types',
        UPDATE: 'update-vehicle-types',
        DELETE: 'delete-vehicle-types',
    },
    MAIL_TEMPLATES: {
        CREATE: 'create-mail-templates',
        BROWSE: 'browse-mail-templates',
        READ: 'read-mail-templates',
        UPDATE: 'update-mail-templates',
        DELETE: 'delete-mail-templates',
    },
    LEGAL: {
        CREATE: 'create-legal-agreements',
        BROWSE: 'browse-legal-agreements',
        READ: 'read-legal-agreements',
        UPDATE: 'update-legal-agreements',
        DELETE: 'delete-legal-agreements',
    },
};
